name: Deployment

on:
  push:
    branches:
      - master

jobs:
  deployment-dropbox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build with gradle
        uses: MrRamych/gradle-actions/openjdk-13@3.1
        with:
          args: build
      - name: Deploy on Dropbox
        run: |
          curl "${UPLOADER_FETCH_URL}" -o "${UPLOADER}" &&
          echo "OAUTH_ACCESS_TOKEN=${DROPBOX_DEPLOY_TOKEN}" > "${UPLOADER_CONFIG}" &&
          bash "${UPLOADER}" -f "${UPLOADER_CONFIG}" mkdir "${TARGET_FOLDER}" &>/dev/null || echo "Target folder exists" &&
          bash "${UPLOADER}" -f "${UPLOADER_CONFIG}" upload build/libs/*-shaded.jar "${TARGET_FOLDER}"
        env:
          TARGET_FOLDER: "/Documents/JARs/NameAsCreated.jar"
          UPLOADER_FETCH_URL: "https://raw.githubusercontent.com/andreafabrizi/Dropbox-Uploader/master/dropbox_uploader.sh"
          UPLOADER: "dropbox_uploader.sh"
          UPLOADER_CONFIG: "dropbox_uploader.cfg"
          DROPBOX_DEPLOY_TOKEN: ${{ secrets.DROPBOX_DEPLOY_TOKEN }}

  deployment-maven:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Publish with gradle
        uses: MrRamych/gradle-actions/openjdk-13@3.1
        with:
          args: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
